version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api-mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-mongodb-cont
    ports:
      - "8080:8080"
    depends_on:
      - mongo
volumes:
  mongodb_data:
